---
timezone: Europe/Kiev
server_username: user
server_git_email: user@example.com
base_required_packages:
  - mc
  - nano
  - htop
  - atop
  - iotop
  - net-tools
  - vim
  - git
  - tig
  - curl
  - wget
  - jq
  - sysstat
  - bash-completion
  - tar
  - unzip
  - ncdu
  - bind-utils
  - yum-utils
  - mlocate
  - firewalld
  - python3
  - python3-pip

selinux_status: disabled   # disabled or permissive

