---
- name: Install nginx program
  package:
    name: 
      - nginx
      - firewalld
    state: present

- name: Generate DH Parameters with a different size (2048 bits)
  openssl_dhparam:
    path: /etc/ssl/certs/dhparam.pem
    size: 2048

- name: Open service https
  firewalld:
    service: https
    permanent: yes
    immediate: yes
    state: enabled

- name: Open service http
  firewalld:
    service: http
    permanent: yes
    immediate: yes
    state: enabled

- name: Disable service dhcpv6-client
  firewalld:
    service: dhcpv6-client
    permanent: yes
    immediate: yes
    state: disabled

- name: Start Nginx service
  service:
    name: nginx
    state: started
    enabled: yes
