---
- name: Install tmux for user (CentOS7)
  vars:
     work_user: "{{ server_username }}"
  import_tasks: tmux_centos7.yml
  when: "(ansible_os_family == 'RedHat') and (ansible_distribution_major_version|int == 7)"

- name: Install tmux for root (CentOS7)
  vars:
     work_user: "root"
  import_tasks: tmux_centos7.yml
  when: "(ansible_os_family == 'RedHat') and (ansible_distribution_major_version|int == 7)"

- name: Install tmux for user (OL8)
  vars:
     work_user: "{{ server_username }}"
  import_tasks: tmux_ol8.yml
  when: "(ansible_os_family == 'RedHat') and (ansible_distribution_major_version|int == 8)"

- name: Install tmux for root (OL8)
  vars:
     work_user: "root"
  import_tasks: tmux_ol8.yml
  when: "(ansible_os_family == 'RedHat') and (ansible_distribution_major_version|int == 8)"
