---
- name: Install programs for Gnome
  yum:
    name: 
      - dconf-editor
      - gnome-tweaks
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-topicons-plus
      - gnome-shell-extension-user-theme 
      - gnome-tweak-tool
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-window-list
      - gnome-shell-extension-common
      - gnome-extensions-app
    state: present

- name: disable auto maximize
  template: 
    src: dconf-settings.j2
    dest: /etc/dconf

- name: update dconf
  shell: dconf update

- name: GSettings 13
  command : "sync"

# tasks file for gnome-restore
- name: Create Background dir
  file: 
    path: "{{ work_dir }}/.local/share/backgrounds"
    owner: "{{ work_user }}"
    group: "{{ work_user }}"
    mode: 0755
    recurse: yes
    state: directory

- name: Copy Background file
  copy:
    src: "{{ item }}"
    dest: "{{ work_dir }}/.local/share/backgrounds/"
    owner: "{{ work_user }}"
    group: "{{ work_user }}"
    mode: 0644
  with_fileglob:
    - "background*.jpg"

- name: download sources
  get_url: 
    url: "https://github.com/brunelli/gnome-shell-extension-installer/raw/master/gnome-shell-extension-installer"
    dest: "/usr/bin/gnome-shell-extension-installer"
    owner: root
    group: root
    mode: 0775

- name: Dock-to-Panel install 
  command: gnome-shell-extension-installer 1160 --yes --restart-shell
  become: true
  become_user: "{{ work_user }}"

- name: AutoHide Battery install
  command: gnome-shell-extension-installer 595 --yes --restart-shell
  become: true
  become_user: "{{ work_user }}"

- name: Enable Gnome Extensions
  command: gsettings set org.gnome.shell enabled-extensions "['background-logo@fedorahosted.org', 'TopIcons@phocean.net', 'dash-to-panel@jderose9.github.com', 'autohide-battery@sitnik.ru']"
  become: true
  become_user: "{{ work_user }}"
  ignore_errors: yes

#- name: Dock-to-Panel enable 
#  command: gnome-extensions enable dash-to-panel@jderose9.github.com
#  become: true
#  become_user: "{{ work_user }}"
#  ignore_errors: yes

#- name: AutoHide Battery enable
#  command: gnome-extensions enable autohide-battery@sitnik.ru
#  become: true
#  become_user: "{{ work_user }}"
#  ignore_errors: yes

# Create dump: dconf dump / > dump_gnome

- name: Check dump_gnome_settings is exists
  stat:
    path: "{{ work_dir }}/dump_gnome_settings"
  register: settings_res

- name: Restore gnome_settings
  shell: "dconf load -f / < {{ work_dir }}/dump_gnome_settings"
  become: yes
  become_user: "{{ work_user }}"
  when: settings_res.stat.exists
  args:
    executable: /bin/bash

- name: Restore dash_to_panel parameters
  shell: "dconf load -f /org/gnome/shell/extensions/dash-to-panel/ < /tmp/dotfiles/src/dash_to_panel_settings"
  become: yes
  become_user: "{{ work_user }}"
  args:
    executable: /bin/bash
