---
- name: Base profile setup (Fedora 37+)
  include_tasks: restore_fedora.yml
  when: "(ansible_distribution == 'Fedora') and (ansible_distribution_major_version|int >= 36)"

- name: Base profile setup (Debian 10+)
  include_tasks: restore_debian.yml
  when: "((ansible_distribution == 'Debian') and (ansible_distribution_major_version|int >= 10)) or ((ansible_distribution == 'Ubuntu') and (ansible_distribution_major_version|int >= 22))"

