---
- name: Install programs for Gnome
  package:
    name: 
      - dconf-editor
      - gnome-tweaks
      - gnome-tweak-tool
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-common
      - gnome-extensions-app
    state: present

- name: get Dash to Panel Extensions
  get_url:
    url:   https://extensions.gnome.org/api/v1/extensions/dash-to-panel@jderose9.github.com/versions/68/?format=zip
    dest: "/tmp/dash-to-panel.zip"
    mode: 0775
    owner: "{{ work_user }}"
    group: "{{ work_user }}"

- name: Enable Gnome Extensions
  command:  gnome-extensions install --force /tmp/dash-to-panel.zip
  become: true
  become_user: "{{ work_user }}"
  ignore_errors: true

- name: Install packege for Gnome configure
  package:
    name: 
      - python3-psutil

- name: Create Background dir
  file: 
    path: "{{ work_dir }}/.local/share/backgrounds"
    owner: "{{ work_user }}"
    group: "{{ work_user }}"
    mode: 0755
    recurse: yes
    state: directory

- name: Copy Background file
  copy:
    src: "{{ item }}"
    dest: "{{ work_dir }}/.local/share/backgrounds/"
    owner: "{{ work_user }}"
    group: "{{ work_user }}"
    mode: 0644
  with_fileglob:
    - "backgrounds/*.jpg"

- name: Ensure GNOME restore script is executable
  ansible.builtin.file:
    path: "{{ work_dir }}/DOD1/r1.restore_gnome_profile_min.sh"
    owner: "{{ work_user }}"
    group: "{{ work_user }}"
    mode: '0755'

- name: Ensure autostart directory exists
  ansible.builtin.file:
    path: "{{ work_dir }}/.config/autostart"
    state: directory
    mode: '0755'
    owner: "{{ work_user }}"
    group: "{{ work_user }}"

- name: Create one-time GNOME restore launcher
  copy:
    dest: "{{ work_dir }}/.config/autostart/gnome-restore-profile.desktop"
    content: |
      [Desktop Entry]
      Type=Application
      Name=Restore GNOME Profile
      Exec=bash -c '{{ work_dir }}/DOD1/r1.restore_gnome_profile_min.sh && rm -f {{ work_dir }}/.config/autostart/gnome-restore-profile.desktop'
      X-GNOME-Autostart-enabled=true
      NoDisplay=false
    mode: '0644'
    owner: "{{ work_user }}"
    group: "{{ work_user }}"


