---
- name: Optimize (Oracle Linux 8; AlmaLinux 8; RockyLinux 8)
  include_tasks: optimize_rpm8.yml
  when: "(ansible_os_family == 'RedHat') and (ansible_distribution_major_version|int == 8)"

- name: Base profile setup (OracleLinux 9; AlmaLinux 9; RockyLinux 9)
  include_tasks: optimize_rpm9.yml
  when: "(ansible_os_family == 'RedHat') and (ansible_distribution_major_version|int == 9)"

- name: Optimize (Fedora 37+)
  include_tasks: optimize_fedora.yml
  when: "(ansible_distribution == 'Fedora') and (ansible_distribution_major_version|int >= 36)"

- name: docker setup (Debian 10+)
  include_tasks: optimize_debian.yml
  when: "((ansible_distribution == 'Debian') and (ansible_distribution_major_version|int >= 10)) or ((ansible_distribution == 'Ubuntu') and (ansible_distribution_major_version|int >= 22))"

- name: Clean /tmp/dotfiles
  file:
    path: "/tmp/dotfiles"
    state: absent






