---
- name: Optimize (Oracle Linux 8)
  import_tasks: optimize_ol8.yml
  when: "(ansible_os_family == 'RedHat') and (ansible_distribution_major_version|int == 8)"

- name: Optimize (Fedora 37+)
  import_tasks: optimize_fedora.yml
  when: "(ansible_distribution == 'Fedora') and (ansible_distribution_major_version|int >= 37)"





