---
- name: Optimize (Oracle Linux 8; AlmaLinux 8; RockyLinux 8)
  include_tasks: optimize_rpm8.yml
  when: "(ansible_os_family == 'RedHat') and (ansible_distribution_major_version|int == 8)"

- name: Base profile setup (OracleLinux 9; AlmaLinux 9; RockyLinux 9)
  include_tasks: base_setup_rpm9.yml
  when: "(ansible_os_family == 'RedHat') and (ansible_distribution_major_version|int == 9)"

- name: Optimize (Fedora 37+)
  include_tasks: optimize_fedora.yml
  when: "(ansible_distribution == 'Fedora') and (ansible_distribution_major_version|int >= 36)"





