---
- name: Install Google Chrome on DEB system
  ansible.builtin.import_tasks: install_deb.yml
  when: ansible_os_family == "Debian"

- name: Install Google Chrome on RPM system
  ansible.builtin.import_tasks: install_rpm.yml
  when: ansible_os_family == "RedHat"
