---
- name: Creating swapiness
  copy:
    dest: "/etc/sysctl.d/95-swapiness-sysctl.conf"
    content: "vm.swappiness=1"
    owner: root
    group: root
    mode: 0644

- name: Creating swapiness
  copy:
    dest: "/etc/sysctl.d/96-vfs-sysctl.conf"
    content: "vm.vfs_cache_pressure=1000"
    owner: root
    group: root
    mode: 0644

- name: Creating swapiness
  copy:
    dest: "/etc/sysctl.d/97-dirty-backgr-sysctl.conf"
    content: "vm.dirty_background_ratio = 10"
    owner: root
    group: root
    mode: 0644

- name: Creating swapiness
  copy:
    dest: "/etc/sysctl.d/98-dirty-ratio-sysctl.conf"
    content: "vm.dirty_ratio = 10"
    owner: root
    group: root
    mode: 0644

- name: Creating swapiness
  ini_file:
    dest: "/etc/systemd/journald.conf"
    section: Journal
    option: SystemMaxUse
    value: "128M"

- name: Run VacuumSize
  command: journalctl --vacuum-size=128M

- name: Create symbolic 11-lcdfilter-default.conf
  file:
    src: "/usr/share/fontconfig/conf.avail/11-lcdfilter-default.conf"
    dest: "/etc/fonts/conf.d/11-lcdfilter-default.conf"
    state: link
