---
- name: vm.swappiness = 60  => sysctl.conf
  sysctl:
    name: vm.swappiness
    value: '60'
    sysctl_set: yes

- name: net.ipv4.ip_forward=1 => sysctl.conf
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes