---
- name: install dependencies (dnf)
  become: true
  dnf:
    name:
      - libdrm
      - libX11-xcb
      - mesa-libgbm
      - which
    state: present

- name: install VS Code repo (dnf)
  become: true
  yum_repository:
    name: code
    description: Visual Studio Code repo
    file: vscode
    baseurl: 'https://packages.microsoft.com//yumrepos/vscode'
    gpgkey: 'https://packages.microsoft.com//keys/microsoft.asc'
    gpgcheck: yes

- name: install VS Code (dnf)
  become: true
  dnf:
    name: "code"
    state: present