---
- name: disable auto maximize
  template: 
    src: dconf-settings.j2
    dest: /etc/dconf

- name: update dconf
  shell: dconf update

- name: GSettings 13
  command : "sync"

- name: enable fedora-updates-modular.repo
  yum_repository:
    name: fedora-updates-modular
    description: fedora-updates-modular
    metalink: https://mirrors.fedoraproject.org/metalink?repo=updates-released-modular-source-f$releasever&arch=$basearch
    enabled: yes

- name: enable fedora-modular.repo
  yum_repository:
    name: fedora-modular
    description: fedora-modular
    metalink: https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-source-$releasever&arch=$basearch
    enabled: yes

- name: download sources
  get_url: 
    url: "https://github.com/brunelli/gnome-shell-extension-installer/raw/master/gnome-shell-extension-installer"
    dest: "/usr/bin/gnome-shell-extension-installer"
    owner: root
    group: root
    mode: 0775
  when: ansible_distribution == 'Fedora' and ansible_distribution_version != '34'


- name: Dock-to-Panel install 
  command: gnome-shell-extension-installer 1160 --yes --restart-shell
  become: true
  become_user: "{{ wrk_username }}"
  when: ansible_distribution == 'Fedora' and ansible_distribution_version != '34'

- name: Dock-to-Panel install
  command: git clone -b "update-to-gnome40" https://github.com/philippun1/dash-to-panel.git dash-to-panel && cd dash-to-panel && make && make install && gnome-extensions enable dash-to-panel@jderose9.github.com
  become: true
  become_user: "{{ wrk_username }}"
  when: ansible_distribution == 'Fedora' and ansible_distribution_version == '34'

- name: DNF Clean ALL
  command: dnf clean all
