---
- name: GSettings 1
  command : "gsettings set org.gnome.settings-daemon.peripherals.keyboard remember-numlock-state true"
  become: true
  become_user: "{{ wrk_username }}"

- name: GSettings 2
  command : "gsettings set org.gnome.gedit.preferences.encodings candidate-encodings \"['UTF-8', 'WINDOWS-1251', 'KOI8-R', 'CURRENT', 'ISO-8859-15', 'UTF-16']'\""
  become: true
  become_user: "{{ wrk_username }}"

- name: GSettings 3
  command : "gsettings set org.gnome.desktop.peripherals.mouse accel-profile 'adaptive'"
  become: true
  become_user: "{{ wrk_username }}"

- name: GSettings 4
  command : "gsettings set org.gnome.desktop.sound allow-volume-above-100-percent true"
  become: true
  become_user: "{{ wrk_username }}"

- name: GSettings 5
  command : "gsettings set org.gnome.desktop.calendar show-weekdate true"
  become: true
  become_user: "{{ wrk_username }}"

- name: GSettings 6
  command : "gsettings set org.gnome.desktop.wm.preferences resize-with-right-button true"
  become: true
  become_user: "{{ wrk_username }}"

- name: GSettings 7
  command : "gsettings set org.gnome.desktop.wm.preferences button-layout 'appmenu:minimize,maximize,close'"
  become: true
  become_user: "{{ wrk_username }}"

- name: GSettings 8
  command : "gsettings set org.gnome.shell.overrides workspaces-only-on-primary falsegsettings set org.gnome.shell.overrides workspaces-only-on-primary false"
  become: true
  become_user: "{{ wrk_username }}"

- name: GSettings 9
  command : "gsettings set org.gnome.nautilus.icon-view default-zoom-level 'standard'"
  become: true
  become_user: "{{ wrk_username }}"

- name: GSettings 10
  command : "gsettings set org.gnome.nautilus.preferences executable-text-activation 'ask'"
  become: true
  become_user: "{{ wrk_username }}"

- name: GSettings 11
  command : "gsettings set org.gtk.Settings.FileChooser sort-directories-first true"
  become: true
  become_user: "{{ wrk_username }}"

- name: GSettings 12
  command : "gsettings set org.gnome.nautilus.list-view use-tree-view true"
  become: true
  become_user: "{{ wrk_username }}"

- name: GSettings 13
  command : "sync"

- name: enable fedora-updates-modular.repo
  yum_repository:
    name: fedora-updates-modular
    description: fedora-updates-modular
    metalink: https://mirrors.fedoraproject.org/metalink?repo=updates-released-modular-source-f$releasever&arch=$basearch
    enabled: yes

- name: enable fedora-modular.repo
  yum_repository:
    name: fedora-modular
    description: fedora-modular
    metalink: https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-source-$releasever&arch=$basearch
    enabled: yes

- name: download sources
  get_url: 
    url: "https://github.com/brunelli/gnome-shell-extension-installer/raw/master/gnome-shell-extension-installer"
    dest: "/usr/bin/gnome-shell-extension-installer"
    owner: root
    group: root
    mode: 0775

- name: Dock-to-Panel install 
  command: gnome-shell-extension-installer 1160 --yes --restart-shell
  become: true
  become_user: "{{ wrk_username }}"

- name: DNF Clean ALL
  command: dnf clean all
