---
- name: hostname_setup
  import_tasks: hostname_configure.yml

- name: selinux configure
  import_tasks: selinux_configure.yml

- name: Base root setup (CentOS7)
  vars:
     work_dir: "/root/"
     work_user: "root"
  import_tasks: base_setup_centos7.yml
  when: "(ansible_os_family == 'RedHat') and (ansible_distribution_major_version|int == 7)"

- name: Base user setup (CentOS7)
  vars:
     work_dir: "/home/{{ server_username }}"
     work_user: "{{ server_username }}"
  import_tasks: base_setup_centos7.yml
  when: "(ansible_os_family == 'RedHat') and (ansible_distribution_major_version|int == 7)"

- name: Base root setup (OL8)
  vars:
     work_dir: "/root/"
     work_user: "root"
  import_tasks: base_setup_ol8.yml
  when: "(ansible_os_family == 'RedHat') and (ansible_distribution_major_version|int == 8)"

- name: Base user setup (OL8)
  vars:
     work_dir: "/home/{{ server_username }}"
     work_user: "{{ server_username }}"
  import_tasks: base_setup_ol8.yml
  when: "(ansible_os_family == 'RedHat') and (ansible_distribution_major_version|int == 8)"

