---
- name: Create local tmp folder
  file:
    src: "/dev/shm"
    dest: "/home/{{ wrk_username }}/tmp"
    state: link

- name: Deploy screenshot script ssarea.sh
  copy:
    src: "ssarea.sh"
    dest: "/usr/bin/ssarea.sh"
    owner: root
    group: root
    mode: 0755
