---
wrk_username: user
base_required_packages:
  - mc
  - nano
  - htop
  - atop
  - iotop
  - vim
  - vim-enhanced
  - net-tools
  - git
  - tig
  - curl
  - wget
  - jq
  - sysstat
  - bash-completion
  - tar
  - unzip
  - ncdu
  - bind-utils
  - yum-utils
  - cifs-utils
  - mlocate
  - firewalld
  - python3
  - python3-pip
  - calc

selinux_status: disabled   # disabled or permissive
timezone: Europe/Kiev

