---
- name: Install GIT
  yum:
    name: "git"
    state: present

- name: Install Galaxy4 repo
  yum:
    name: "http://galaxy4.net/repo/galaxy4-release-{{ansible_distribution_major_version}}-current.noarch.rpm"
    state: present

- name: install tmux packages
  yum:
    name: "tmux"
    state: present

- name: Clone tmux-config repository
  git:
    repo: 'https://github.com/laspavel/tmux-config.git'
    dest: /tmp/tmux-config
    clone: yes
    update: yes

- name: install tmux-config 
  shell: "/tmp/tmux-config/install.sh"
  args:
    executable: /bin/bash
