---
- name: Add new users
  user:
    name: "{{ server_username }}"
    comment: User account
    shell: /bin/bash
    system: no
    createhome: yes
    home: "/home/{{ server_username }}"
    state: present

- name: Creates destination directory
  file:
    state: directory
    mode: 0700
    dest: /home/{{ server_username }}/.ssh/

- name: Generate RSA key for main user
  command : "ssh-keygen -q -t rsa -b 4096 -f /home/{{ server_username }}/.ssh/id_rsa -C \"{{ server_git_email }}\" -N \"\""
  args:
    creates: /home/{{ server_username }}/.ssh/id_rsa
