---
- name: Creates destination directory
  file:
    state: directory
    mode: 0700
    dest: /root/.ssh/

- name: Generate RSA key for main user
  command : "ssh-keygen -q -t rsa -b 4096 -f /root/.ssh/id_rsa -C \"{{ git_email }}\" -N \"\""
  args:
    creates: /root/.ssh/id_rsa
