git_email: laspavel@gmail.com
git_name: laspavel
hostname_: homebook
timezone: Europe/Kiev

create_id_rsa: true
create_tmp_folder_in_home: true

docker_users:
  - "{{ work_user }}"

base_required_packages:
- binutils 
- cronie
- gcc 
- make 
- patch
- calc
- libgomp
- glibc-headers
- glibc-devel 
- kernel-headers
- kernel-devel
- dkms 
- doublecmd-gtk 
- google-chrome-stable
- htop
- mc
- nano
- sshfs
- davfs2
- unrar
- foliate
- meld
- whois
- flatpak
- traceroute
- git
- tig
- vim-enhanced
- curl
#- tlp
#- tlp-rdw
- arj
- cabextract
- p7zip
- p7zip-plugins
- wine 
- gparted
- langpacks-ru
- wget
- file-roller-nautilus
# - fuse-exfat
- gvfs-fuse
- gvfs-mtp
- gvfs-nfs
- gvfs-smb
- ansible
# - lpf-mscore-fonts
- qbittorrent
- gnome-calendar
- uget
- evince-djvu
- unar
- redshift
# - freetype-freeworld
- firewalld
- dnf-plugins-core
- python3-devel
# - VirtualBox
- kubernetes-client
- remmina
- ecryptfs-utils
- lnav
