git_email: laspavel@gmail.com
git_name: laspavel
hostname_: main-gg
timezone: Europe/Kiev

docker_users:
  - "{{ work_user }}"

base_required_packages:
  - mc
  - nano
  - htop
  - atop
  - iotop
  - net-tools
  - vim
  - git
  - tig
  - curl
  - wget
  - jq
  - sysstat
  - procps
  - bash-completion
  - tar
  - unzip
  - ncdu
  - bind9utils
  - mlocate
  - firewalld
  - python3
  - python3-pip
  - whois
  - traceroute
  - cifs-utils
  - certbot
  - nginx
  - cockpit
