git_email: laspavel@gmail.com
git_name: laspavel
hostname_: homebook
timezone: Europe/Kiev

create_id_rsa: true
create_tmp_folder_in_home: true

docker_users:
  - "{{ work_user }}"

base_required_packages:
  - mc
  - nano
  - htop
  - atop
  - iotop
  - net-tools
  - vim
  - vim-enhanced
  - git
  - tig
  - curl
  - wget
  - jq
  - sysstat
  - procps
  - bash-completion
  - sudo
  - tar
  - unzip
  - ncdu
  - bind-utils
  - mlocate
  - firewalld
  - python3
  - python3-pip
  - python3-devel
  - cifs-utils
  - cronie
  - binutils 
  - gcc 
  - make 
  - patch
  - libgomp
  - glibc-headers
  - glibc-devel 
  - kernel-headers
  - kernel-devel
  - dkms 
  - doublecmd-gtk 
  - sshfs
  - davfs2
  - unrar
  - meld
  - whois
  - flatpak
  - traceroute
  - vim-enhanced
  - arj
  - cabextract
  - p7zip
  - p7zip-plugins
  - wine 
  - gparted
  - langpacks-ru
  - file-roller-nautilus
  - gvfs-fuse
  - gvfs-mtp
  - gvfs-nfs
  - gvfs-smb
  - ansible
  - qbittorrent
  - gnome-calendar
  - evince-djvu
  - unar
  - redshift
  - dnf-plugins-core
  - remmina
  - ecryptfs-utils
