git_email: laspavel@gmail.com
git_name: laspavel
hostname_: homebook
timezone: Europe/Kiev

create_id_rsa: true
create_tmp_folder_in_home: true

docker_users:
  - "{{ work_user }}"

base_required_packages:
  - mc
  - nano
  - htop
  - atop
  - iotop
  - net-tools
  - vim
  - git
  - tig
  - curl
  - wget
  - jq
  - yq
  - sysstat
  - procps
  - bash-completion
  - sudo
  - tar
  - unzip
  - ncdu
  - bind9utils
  - mlocate
  - firewalld
  - python3
  - python3-pip
  - python3-dev
  - cifs-utils
  - locales-all
  - binutils 
  - gcc 
  - make 
  - patch
  - dkms 
  - doublecmd-gtk 
  - sshfs
  - davfs2
  - unrar
  - meld
  - whois
  - flatpak
  - traceroute
  - arj
  - cabextract
  - p7zip
  - wine 
  - gparted
  - gvfs-fuse
  - ansible
  - qbittorrent
  - gnome-calendar
  - uget
  - unar
  - remmina
  - ecryptfs-utils
