git_email: laspavel@gmail.com
git_name: laspavel
hostname_: homebook
timezone: Europe/Kiev

docker_users:
  - "{{ work_user }}"

base_required_packages:
- binutils 
- cronie
- gcc 
- make 
- patch
- calc
- libgomp
- glibc-headers
- glibc-devel 
- kernel-headers
- kernel-devel
- dkms 
- qt5-qtx11extras
- libxkbcommon
- doublecmd-gtk 
- google-chrome-stable
- htop
- mc
- nano
- sshfs
- davfs2
- unrar
- foliate
- meld
- whois
- flatpak
- traceroute
- git
- tig
- vim-enhanced
- openvpn
- curl
- tlp
- tlp-rdw
- arj
- cabextract
- p7zip
- p7zip-plugins
- wine 
- gparted
- langpacks-ru
- pavucontrol
- wget
#- ffmpeg
- file-roller-nautilus
- fuse-exfat
- gvfs-fuse
- gvfs-mtp
- gvfs-nfs
- gvfs-smb
- ansible
- lpf-mscore-fonts
- qbittorrent
- gnome-calendar
- uget
- evince-djvu
- unar
- flameshot 
- redshift
- freetype-freeworld
- firewalld
- dnf-plugins-core
- python3-devel
- VirtualBox
- asciinema
- kubernetes-client
- remmina
- ecryptfs-utils
- lnav
- dnf-automatic