- name: K8S All setup (User)
  vars:
     work_dir: "/home/{{ server_username }}"
     work_user: "{{ server_username }}"
  import_tasks: k8s_tools_setup.yml

- name: K8S All setup (Root)
  vars:
     work_dir: "/root/"
     work_user: "root"
  import_tasks: k8s_tools_setup.yml
