---
- name: Create local bin directory
  file:
    path: "{{ work_dir }}/.local/bin"
    owner: "{{ work_user }}"
    group: "{{ work_user }}"
    state: directory
    mode: 0755

- name: Create local bash.autocomplete.d directory
  file:
    path: "{{ work_dir }}/.local/.bash.autocomplete.d"
    owner: "{{ work_user }}"
    group: "{{ work_user }}"
    state: directory
    mode: 0755

- name: Download KUBECTX Utils from Github
  unarchive:
    src: "{{ kubectx_binary_download_url }}"
    dest: "{{ work_dir }}"
    mode: 0755
    remote_src: yes
  changed_when: false

- name: Copy KUBECTX file to local bin folder
  copy:
    src: "{{ work_dir }}/kubectx-{{ kubectx_binary_version }}/kubectx"
    dest: "{{ work_dir }}/.local/bin/kubectx"
    mode: 0755
  changed_when: false

- name: Copy KUBENS file to local bin folder
  copy:
    src: "{{ work_dir }}/kubectx-{{ kubectx_binary_version }}/kubens"
    dest: "{{ work_dir }}/.local/bin/kubens"
    mode: 0755
  changed_when: false

- name: Deploy autocompletion
  copy:
    src: "{{ item }}"
    dest: "{{ work_dir }}/.local/.bash.autocomplete.d"
    owner: "{{ work_user }}"
    group: "{{ work_user }}"
    mode: 0644
  with_fileglob:
    - ".bash.autocomplete.d/*.*"

- name: Remove old CUBECTX download files
  file:
    path: "{{ work_dir }}/kubectx-{{ kubectx_binary_version }}"
    state: absent

- name: Download K9S Binary from Github
  unarchive:
    src: "{{ k9s_binary_download_url }}"
    dest: "{{ work_dir }}/.local/bin"
    mode: 0755
    remote_src: yes
  changed_when: false

- name: Download RKE Binary from Github
  get_url:
    url: "{{ rke_binary_download_url }}"
    dest: "{{ work_dir }}/.local/bin/rke"
    mode: 0755
  changed_when: false

- name: Download Helmfile Binary from Github
  get_url:
    url: "{{ helmfile_binary_download_url }}"
    dest: "{{ work_dir }}/.local/bin/helmfile"
    mode: 0755
  changed_when: false

#- name: Download Stern Binary from Github
#  get_url:
#    url: "{{ stern_binary_download_url }}"
#    dest: "{{ work_dir }}/.local/bin/stern"
#    mode: 0755
 # changed_when: false

- name: Download kubectl binary
  get_url:
    url: "{{ kubectl_binary_download_url }}"
    dest: "{{ work_dir }}/.local/bin/kubectl"
    mode: 0755
  changed_when: false

- name: Retrieve helm binary archive.
  unarchive:
    src: "{{ helm_binary_download_url }}"
    dest: "./"
    remote_src: yes
  changed_when: false
  check_mode: no

- name: Move helm binary into place.
  copy:
    src: linux-amd64/helm
    dest: "{{ work_dir }}/.local/bin/helm"
    mode: 0755
  changed_when: false

- name: terraform install
  unarchive:
    src: "{{ terraform_binary_download_url }}"
    dest: "{{ work_dir }}/.local/bin"
    mode: 0755
    remote_src: True
  changed_when: false

- name: Remove old download files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - ./linux-amd64
    - ./LICENSE
    - ./README.md

- name: Create additional scripts directory
  file:
    path: "{{ work_dir }}/.local/scripts"
    owner: "{{ work_user }}"
    group: "{{ work_user }}"
    state: directory
    mode: 0755

- name: Deploy additional scripts
  copy:
    src: "{{ item }}"
    dest: "{{ work_dir }}/.local/scripts"
    owner: "{{ work_user }}"
    group: "{{ work_user }}"
    mode: 0755
  with_fileglob:
    - "scripts/*.*"

