---
- name: Install certbot program
  package:
    name: 
      - certbot
    state: present

- name: Create certbot config
  copy:
    content: |
            location ^~ /.well-known/acme-challenge/ {
                default_type "text/plain";
                root /usr/share/nginx/html;
            }
    dest: /etc/nginx/certbot.conf

#- name: Inserting a certbot line in default config
#  lineinfile:
#    path: /etc/nginx/nginx.conf
#    line: include /etc/nginx/certbot.conf;
#    insertafter: root         /usr/share/nginx/html;

- name: Install certbot renew hook
  copy:
    content: |
            00 3 * * * root certbot renew --post-hook "systemctl reload nginx"
    dest: /etc/cron.d/certbot_renew
    owner: root
    group: root
    mode: '644'
