---
- name: Create groups
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ work_groups }}"

- name: Add new user
  user:
    name: "{{ work_user }}"
    comment: "{{ work_user }}"
    groups: "{{ work_user }}"
    password: "{{ passwd_user | string | password_hash('sha512') }}"
    shell: /bin/bash
    system: no
    createhome: yes
    home: "{{ work_dir }}"
    append: yes
    update_password: always
    state: present

- name: Creates destination directory
  file:
    state: directory
    mode: 0700
    dest: "{{ work_dir }}/.ssh/"
    owner: "{{ work_user }}"
    group: "{{ work_user }}"

- name: Get Hostname got ssh-keygen
  ansible.builtin.gather_facts:
  when: create_id_rsa is defined

- name: Generate RSA key for main user
  command : "ssh-keygen -q -t rsa -b 4096 -f {{ work_dir }}/.ssh/id_rsa -C \"{{ work_user }}@{{ ansible_hostname }}\" -N \"\""
  become: true
  become_user: "{{ work_user }}"
  args:
    executable: /bin/bash
    creates: "{{ work_dir }}/.ssh/id_rsa"
  when: create_id_rsa is defined

