---
- name: Copy my sysctl configuration
  copy:
    src: "50.sysctl_{{ sysctl_typecfg }}.conf"
    dest: "/etc/sysctl.d"
    owner: "root"
    group: "root"
    mode: '0644'
    force: yes
  notify:
    - Reload sysctl configuration
  
#- name: vm.swappiness = 60  => sysctl.conf
#  sysctl:
#    name: vm.swappiness
#    value: '60'
#    sysctl_set: yes

- name: Updating journald
  ini_file:
    dest: "/etc/systemd/journald.conf"
    section: Journal
    option: SystemMaxUse
    value: "128M"
  
- name: Run VacuumSize
  command: journalctl --vacuum-size=128M