---
# tasks file for kde-restore
- name: Install the 'KDE Desktop environment' package group
  yum:
    name: "@kde-desktop-environment"
    state: present

- name: KDE configs restore
  copy:
    src: kdeconfig/
    dest: home/{{ wrk_username }}/
    remote_src: yes
    directory_mode: yes
    mode: '0644'
    owner: "{{ wrk_username }}"
    group: "{{ wrk_username }}"
    
 

