---
# tasks file for kde-restore
- name: Install the 'KDE Desktop environment' package group
  yum:
    name: "@kde-desktop-environment"
    state: present

- name: KDE configs restore
  copy:
    src: kdeconfigs/
    dest: /home/{{ wrk_username }}/
    mode: '0644'
    owner: "{{ wrk_username }}"
    group: "{{ wrk_username }}"
    
 

