---
- name: Upgrade system
  yum:
    name: '*'
    state: latest
    exclude: kernel*

- name: Install epel-release
  yum:
    name:
        - epel-release
    state: latest

- name: Install minimal programs
  yum:
    name: "{{ base_required_packages }}"
    state: present

- name: Set required timezone
  timezone:
    name: "{{ timezone }}"

- name: Set required Selinux status
  selinux:
    policy: targeted
    state: "{{ selinux_status }}"
