---
- name: Base profile setup (Oracle Linux 8; AlmaLinux 8; RockyLinux 8)
  include_tasks: profile_conf_rpm8.yml
  when: "(ansible_os_family == 'RedHat') and (ansible_distribution_major_version|int == 8)"

- name: Base profile setup (Fedora 37+)
  include_tasks: profile_conf_fedora.yml
  when: "(ansible_distribution == 'Fedora') and (ansible_distribution_major_version|int >= 36)"

- name: Base profile setup (Debian 10+)
  include_tasks: profile_conf_debian.yml
  when: "(ansible_distribution == 'Debian') and (ansible_distribution_major_version|int >= 10)"