---
- name: Base profile setup (OL8)
  include_tasks: profile_conf_ol8.yml
  when: "(ansible_os_family == 'RedHat') and (ansible_distribution_major_version|int == 8)"

- name: Base profile setup (Fedora 37+)
  include_tasks: profile_conf_fedora.yml
  when: "(ansible_distribution == 'Fedora') and (ansible_distribution_major_version|int >= 37)"
