---
- name: Install VIM 
  yum:
    name:
      - vim
      - vim-enhanced
    state: present

- name: Install GIT 
  yum:
    name:
      - git
    state: present

- name: Clone dotfiles repository
  git:
    repo: "https://github.com/laspavel/dotfiles.git"
    dest: /tmp/dotfiles
    clone: yes
    update: yes
    depth: 1

- name: Copy dotfiles to user home directory
  copy:
    src: "/tmp/dotfiles/src/"
    dest: "{{ work_dir }}"
    owner: "{{ work_user }}"
    group: "{{ work_user }}"
    force: yes
  ignore_errors: true

- name: Creates directory Vim-plug
  file:
    path: "{{ work_dir }}/.vim/autoload/"
    state: directory
    mode: "0775"
    owner: "{{ work_user }}"
    group: "{{ work_user }}"

- name: Creates directory local bin
  file:
    path: "{{ work_dir }}/.local/bin/"
    state: directory
    mode: "0775"
    owner: "{{ work_user }}"
    group: "{{ work_user }}"

- name: Configure Vim-plug
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{ work_dir }}/.vim/autoload/plug.vim"
    mode: "0775"
    owner: "{{ work_user }}"
    group: "{{ work_user }}"

- name: Delete old vim plugged folder
  file:
    state: absent
    dest: "{{ work_dir }}/.vim/plugged"

- name: Install Plugin
  shell: "vim +'PlugInstall --sync' +qall &> /dev/null"
  become: yes
  become_user: "{{ work_user }}"
  args:
    executable: /bin/bash

- name: mkdir SSH config directory
  file:
    state: directory
    owner: "{{ work_user }}"
    group: "{{ work_user }}"
    mode: "0700"
    dest: "{{ work_dir }}/.ssh/"

- name: Creates directory local bin
  file:
    path: "{{ work_dir }}/.local/bin/"
    state: directory
    mode: "0775"
    owner: "{{ work_user }}"
    group: "{{ work_user }}"
