---
- name: Install the 'Development tools' package group
  package:
    name: 
      - build-essential
      - autoconf
      - automake 
      - gdb 
      - libffi-dev 
      - zlib1g-dev
      - libssl-dev
    state: present

- name: start the sshd service and enable it
  systemd:
    name: sshd
    state: started
    enabled: yes

- name: start the firewalld service and enable it
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Install VIM packages
  package:
    name:
      - vim
    state: present

- name: Clone dotfiles repository
  git:
    repo: "https://github.com/laspavel/dotfiles.git"
    dest: /tmp/dotfiles
    clone: yes
    update: yes
    depth: 1

- name: Copy dotfiles to user home directory
  copy:
    src: "/tmp/dotfiles/src/"
    dest: "{{ work_dir }}"
    owner: "{{ work_user }}"
    group: "{{ work_user }}"
    force: yes
  ignore_errors: true

- name: Creates directory Vim-plug
  file:
    path: "{{ work_dir }}/.vim/autoload/"
    state: directory
    mode: "0775"
    owner: "{{ work_user }}"
    group: "{{ work_user }}"

- name: Creates directory local bin
  file:
    path: "{{ work_dir }}/.local/bin/"
    state: directory
    mode: "0775"
    owner: "{{ work_user }}"
    group: "{{ work_user }}"

- name: Configure Vim-plug
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{ work_dir }}/.vim/autoload/plug.vim"
    mode: "0775"
    owner: "{{ work_user }}"
    group: "{{ work_user }}"

- name: Delete old vim plugged folder
  file:
    state: absent
    dest: "{{ work_dir }}/.vim/plugged"

- name: Install Plugin
  shell: "vim +'PlugInstall --sync' +qall &> /dev/null"
  become: yes
  become_user: "{{ work_user }}"
  args:
    executable: /bin/bash

- name: mkdir SSH config directory
  file:
    state: directory
    owner: "{{ work_user }}"
    mode: "0700"
    recurse: yes
    dest: "{{ work_dir }}/.ssh/"

- name: Configure Git Autocomplete
  get_url:
    url: "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash"
    dest: "/etc/bash_completion.d/git-completion.bash"
    mode: "0664"
  changed_when: false

- name: Creates directory local bin
  file:
    path: "{{ work_dir }}/.local/bin/"
    state: directory
    mode: "0775"
    owner: "{{ work_user }}"
    group: "{{ work_user }}"
