---
- name: Install tmux (Oracle Linux 8)
  include_tasks: tmux_ol8.yml
  when: "(ansible_os_family == 'RedHat') and (ansible_distribution_major_version|int == 8)"

- name: Install tmux (Fedora 37+)
  include_tasks: tmux_fedora.yml
  when: "(ansible_distribution == 'Fedora') and (ansible_distribution_major_version|int >= 36)"

- name: Install tmux (Debian 10+)
  include_tasks: tmux_debian.yml
  when: "(ansible_distribution == 'Debian') and (ansible_distribution_major_version|int >= 10)"