---
- name: Install GIT
  yum:
    name: git
    state: present

- name: install tmux packages
  yum:
    name: tmux
    state: present

- name: Clone tmux-config repository
  git:
    repo: https://github.com/laspavel/tmux-config.git
    dest: /tmp/tmux-config
    clone: yes
    update: yes
    depth: 1

- name: install tmux-config 
  shell: /tmp/tmux-config/install.sh
  become: true
  become_user: "{{ work_user }}"
  args:
    executable: /bin/bash

- name: Clean /tmp
  file:
    path: "/tmp/tmux-config"
    state: absent