---
- name: Install epel-release
  yum:
    name:
        - epel-release
    state: latest

- name: Install GIT
  yum:
    name: "git"
    state: present

- name: Copy tmux package (Oracle Linux 8)
  copy:
    src: tmux-3.2-1.el8.x86_64.rpm
    dest: /tmp/tmux-3.2-1.el8.x86_64.rpm
    owner: root
    group: root
    mode: '0644'

- name: Install tmux packages (Oracle Linux 8)
  yum:
    name: "/tmp/tmux-3.2-1.el8.x86_64.rpm"
    state: present
    disable_gpg_check: yes

- name: Clone tmux-config repository
  git:
    repo: 'https://github.com/laspavel/tmux-config.git'
    dest: /tmp/tmux-config
    clone: yes
    update: yes

- name: install tmux-config 
  shell: "/tmp/tmux-config/install.sh"
  become: yes
  become_user: "{{ work_user }}"
  args:
    executable: /bin/bash
