---
- name: Set required hostname
  hostname:
    name: "{{ hostname_ }}"
  when: (hostname_ is defined)

- name: Set required Selinux status
  selinux:
    policy: targeted
    state: "{{ selinux_status }}"

- name: YUM Clean ALL
  command: yum clean all
  args:
    warn: false

- name: YUM Make chache
  command: yum makecache
  args:
    warn: false

- name: Upgrade system
  yum:
    name: "*"
    state: latest
    exclude: kernel*

- name: Install epel-release
  yum:
    name:
      - epel-release
    state: latest

- name: Install minimal programs
  yum:
    name: "{{ base_required_packages }}"
    state: present

- name: Install the 'Development tools' package group
  yum:
    name: "@Development tools"
    state: present

- name: Install mlocate package
  yum:
    name: "mlocate"
    state: present

- name: Set required timezone
  timezone:
    name: "{{ timezone }}"

- name: start the sshd service and enable it
  systemd:
    name: sshd
    state: started
    enabled: yes

- name: start the firewalld service and enable it
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Open port for SSH
  firewalld:
    service: ssh
    permanent: yes
    state: enabled
    immediate: yes

- name: Install git
  yum:
    name: git
    state: present

- name: Configure Git Autocomplete
  get_url:
    url: "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash"
    dest: "/etc/bash_completion.d/git-completion.bash"
    mode: "0664"
  changed_when: false

- name: Install console langpack
  yum:
    name: glibc-langpack-ru
    state: present

- name: set-locale
  command: localectl set-locale LANG=ru_RU.utf8
  args:
    warn: false

- name: Set vconsole font
  lineinfile:
    regexp: '^[ #]*FONT='
    line: 'FONT="UniCyr_8x16"'
    dest: '/etc/vconsole.conf'
    create: true
    mode: '644'
