---
- name: Set required hostname
  hostname:
    name: "{{ hostname_ }}"
  when: (hostname_ is defined)

- name: apt update
  become: "True"
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600

- name: Install minimal programs
  package:
    name: "{{ base_required_packages }}"
    state: present

- name: Set required timezone
  timezone:
    name: "{{ timezone }}"

- name: start the sshd service and enable it
  systemd:
    name: sshd
    state: started
    enabled: yes

- name: start the firewalld service and enable it
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Install git
  package:
    name: git
    state: present
