---
- name: Set required hostname
  hostname:
    name: "{{ hostname_ }}"
  when: (hostname_ is defined)

- name: apt update
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600

- name: Install minimal programs
  package:
    name: "{{ base_required_packages }}"
    state: present

- name: Install the 'Development tools' package group
  package:
    name: 
      - build-essential
      - autoconf
      - automake 
      - gdb 
      - libffi-dev 
      - zlib1g-dev
      - libssl-dev
    state: present

- name: Set required timezone
  timezone:
    name: "{{ timezone }}"
  when: (timezone is defined)

- name: start the sshd service and enable it
  systemd:
    name: sshd
    state: started
    enabled: yes

- name: start the firewalld service and enable it
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Open port for SSH
  firewalld:
    service: ssh
    permanent: yes
    state: enabled
    immediate: yes

- name: Install git
  package:
    name: git
    state: present

- name: Create local bash.autocomplete.d directory
  file:
    path: "{{ work_dir }}/.local/.bash.autocomplete.d"
    owner: "{{ work_user }}"
    group: "{{ work_user }}"
    state: directory
    mode: 0755

- name: Configure Git Autocomplete
  get_url:
    url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
    dest: "{{ work_dir }}/.local/.bash.autocomplete.d/git-completion.bash"
    mode: 0664
  changed_when: false
